version: 0.2

phases:
  pre_build:
    commands:
      - npm install
      - npm i gulp
  build:
    commands:
      - gulp

artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: ./